# Generated by Django 5.2.14 on 2026-05-26 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da categoria')),
                ('descricao', models.TextField(verbose_name='Descrição da categoria')),
            ],
            options={
                'verbose_name': 'Categoria do Objeto',
                'verbose_name_plural': 'Categorias dos Objetos',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da pessoa')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF da pessoa')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone da pessoa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email da pessoa')),
                ('ocupacao', models.CharField(choices=[('usuario', 'Usuário'), ('funcionario', 'Funcionário'), ('admin', 'Administrador')], max_length=20, verbose_name='Ocupação da pessoa')),
                ('data_cadastro', models.DateField(verbose_name='Data de cadastro')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='StatusObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do status')),
                ('descricao', models.TextField(verbose_name='Descrição do status')),
            ],
            options={
                'verbose_name': 'Status do Objeto',
                'verbose_name_plural': 'Status dos Objetos',
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade do bairro')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da instituição')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo da instituição')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone da instituição')),
                ('email', models.EmailField(max_length=254, verbose_name='Email da instituição')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço da instituição')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bairro', verbose_name='Bairro da instituição')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade da instituição')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do local')),
                ('descricao', models.TextField(verbose_name='Descrição do local')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao', verbose_name='Instituição do local')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do objeto')),
                ('descricao', models.TextField(verbose_name='Descrição do objeto')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor do objeto')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca do objeto')),
                ('imagem', models.ImageField(upload_to='objetos/', verbose_name='Imagem do objeto')),
                ('data_registro', models.DateField(verbose_name='Data de registro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoriaobjeto', verbose_name='Categoria do objeto')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.local', verbose_name='Local do objeto')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa responsável')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.statusobjeto', verbose_name='Status do objeto')),
            ],
            options={
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='evidencias/', verbose_name='Imagem da evidência')),
                ('descricao', models.TextField(verbose_name='Descrição da evidência')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objeto', verbose_name='Objeto')),
            ],
            options={
                'verbose_name': 'Evidência',
                'verbose_name_plural': 'Evidências',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateField(verbose_name='Data de envio')),
                ('visualizada', models.BooleanField(verbose_name='Notificação visualizada')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto do comentário')),
                ('data', models.DateField(verbose_name='Data do comentário')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objeto', verbose_name='Objeto')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
        migrations.CreateModel(
            name='RegistroEncontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_encontro', models.DateField(verbose_name='Data do encontro')),
                ('observacao', models.TextField(verbose_name='Observação')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objeto', verbose_name='Objeto encontrado')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa responsável')),
            ],
            options={
                'verbose_name': 'Registro Encontrado',
                'verbose_name_plural': 'Registros Encontrados',
            },
        ),
        migrations.CreateModel(
            name='RegistroPerda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_perda', models.DateField(verbose_name='Data da perda')),
                ('descricao', models.TextField(verbose_name='Descrição da perda')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objeto', verbose_name='Objeto perdido')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Registro de Perda',
                'verbose_name_plural': 'Registros de Perdas',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do setor')),
                ('descricao', models.TextField(verbose_name='Descrição do setor')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao', verbose_name='Instituição do setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.AddField(
            model_name='local',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.setor', verbose_name='Setor do local'),
        ),
        migrations.CreateModel(
            name='SolicitacaoPosse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da solicitação')),
                ('data_solicitacao', models.DateField(verbose_name='Data da solicitação')),
                ('aprovada', models.BooleanField(verbose_name='Solicitação aprovada')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objeto', verbose_name='Objeto')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Solicitação de Posse',
                'verbose_name_plural': 'Solicitações de Posse',
            },
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da movimentação')),
                ('descricao', models.TextField(verbose_name='Descrição da movimentação')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objeto', verbose_name='Objeto')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa responsável')),
                ('status_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_anterior', to='app.statusobjeto', verbose_name='Status anterior')),
                ('status_novo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_novo', to='app.statusobjeto', verbose_name='Novo status')),
            ],
            options={
                'verbose_name': 'Histórico de Movimentação',
                'verbose_name_plural': 'Históricos de Movimentações',
            },
        ),
        migrations.CreateModel(
            name='TipoObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do tipo')),
                ('descricao', models.TextField(verbose_name='Descrição do tipo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoriaobjeto', verbose_name='Categoria do tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Objeto',
                'verbose_name_plural': 'Tipos de Objetos',
            },
        ),
        migrations.AddField(
            model_name='objeto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoobjeto', verbose_name='Tipo do objeto'),
        ),
    ]
