# Generated by Django 5.2.14 on 2026-05-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da categoria')),
                ('descricao', models.TextField(verbose_name='Descrição da categoria')),
            ],
            options={
                'verbose_name': 'Categoria do Objeto',
                'verbose_name_plural': 'Categorias dos Objetos',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da instituição')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo da instituição')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone da instituição')),
                ('email', models.EmailField(max_length=254, verbose_name='Email da instituição')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço da instituição')),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da pessoa')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF da pessoa')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone da pessoa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email da pessoa')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='StatusObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do status')),
                ('descricao', models.TextField(verbose_name='Descrição do status')),
            ],
            options={
                'verbose_name': 'Status do Objeto',
                'verbose_name_plural': 'Status dos Objetos',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo do funcionário')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao', verbose_name='Instituição do funcionário')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa do funcionário')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do local')),
                ('descricao', models.TextField(verbose_name='Descrição do local')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao', verbose_name='Instituição do local')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do objeto')),
                ('descricao', models.TextField(verbose_name='Descrição do objeto')),
                ('cor', models.CharField(max_length=50, verbose_name='Cor do objeto')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca do objeto')),
                ('imagem', models.ImageField(upload_to='objetos/', verbose_name='Imagem do objeto')),
                ('data_registro', models.DateField(verbose_name='Data de registro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoriaobjeto', verbose_name='Categoria do objeto')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.local', verbose_name='Local do objeto')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.statusobjeto', verbose_name='Status do objeto')),
            ],
            options={
                'verbose_name': 'Objeto',
                'verbose_name_plural': 'Objetos',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='evidencias/', verbose_name='Imagem da evidência')),
                ('descricao', models.TextField(verbose_name='Descrição da evidência')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objeto', verbose_name='Objeto')),
            ],
            options={
                'verbose_name': 'Evidência',
                'verbose_name_plural': 'Evidências',
            },
        ),
        migrations.CreateModel(
            name='RegistroEncontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_encontro', models.DateField(verbose_name='Data do encontro')),
                ('observacao', models.TextField(verbose_name='Observação')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcionario', verbose_name='Funcionário')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objeto', verbose_name='Objeto encontrado')),
            ],
            options={
                'verbose_name': 'Registro Encontrado',
                'verbose_name_plural': 'Registros Encontrados',
            },
        ),
        migrations.CreateModel(
            name='HistoricoMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da movimentação')),
                ('descricao', models.TextField(verbose_name='Descrição da movimentação')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcionario', verbose_name='Funcionário')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objeto', verbose_name='Objeto')),
                ('status_anterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_anterior', to='app.statusobjeto', verbose_name='Status anterior')),
                ('status_novo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_novo', to='app.statusobjeto', verbose_name='Novo status')),
            ],
            options={
                'verbose_name': 'Histórico de Movimentação',
                'verbose_name_plural': 'Históricos de Movimentações',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(verbose_name='Data de cadastro')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa do usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='RegistroPerda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_perda', models.DateField(verbose_name='Data da perda')),
                ('descricao', models.TextField(verbose_name='Descrição da perda')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objeto', verbose_name='Objeto perdido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Perda',
                'verbose_name_plural': 'Registros de Perdas',
            },
        ),
        migrations.AddField(
            model_name='objeto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário do objeto'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto do comentário')),
                ('data', models.DateField(verbose_name='Data do comentário')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objeto', verbose_name='Objeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
    ]
