# Generated by Django 5.2.14 on 2026-06-09 17:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroperda',
            name='data_perda',
        ),
        migrations.AddField(
            model_name='registroperda',
            name='data_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroperda',
            name='local',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.local'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objeto',
            name='data_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registroencontrado',
            name='data_encontro',
            field=models.DateField(auto_now_add=True, verbose_name='Data do encontro'),
        ),
        migrations.AlterField(
            model_name='registroencontrado',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='registroperda',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroperda',
            name='objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objeto'),
        ),
        migrations.AlterField(
            model_name='registroperda',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa'),
        ),
    ]
