# Generated by Django 5.2.14 on 2026-06-09 18:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_registroperda_data_perda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='data_envio',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da evidência'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Data do comentário'),
        ),
        migrations.AlterField(
            model_name='historicomovimentacao',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Data da movimentação'),
        ),
        migrations.AlterField(
            model_name='historicomovimentacao',
            name='status_anterior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status_anterior', to='app.statusobjeto', verbose_name='Status anterior'),
        ),
        migrations.AlterField(
            model_name='historicomovimentacao',
            name='status_novo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status_novo', to='app.statusobjeto', verbose_name='Novo status'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_envio',
            field=models.DateField(auto_now_add=True, verbose_name='Data de envio'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='visualizada',
            field=models.BooleanField(default=False, verbose_name='Notificação visualizada'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='data_registro',
            field=models.DateField(auto_now_add=True, verbose_name='Data de registro'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='objetos/', verbose_name='Imagem do objeto'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='registroencontrado',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='registroperda',
            name='data_registro',
            field=models.DateField(auto_now_add=True, verbose_name='Data do registro'),
        ),
        migrations.AlterField(
            model_name='registroperda',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='registroperda',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.local', verbose_name='Local da perda'),
        ),
        migrations.AlterField(
            model_name='registroperda',
            name='objeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objeto', verbose_name='Objeto perdido'),
        ),
        migrations.AlterField(
            model_name='registroperda',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa responsável'),
        ),
        migrations.AlterField(
            model_name='solicitacaoposse',
            name='aprovada',
            field=models.BooleanField(default=False, verbose_name='Solicitação aprovada'),
        ),
        migrations.AlterField(
            model_name='solicitacaoposse',
            name='data_solicitacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data da solicitação'),
        ),
    ]
